/// UI strings in Uzbek and Russian.
///
/// English exists only for developer-facing surfaces. Every clinical string a
/// clinician sees must exist in both uz and ru; `test/strings_test.dart`
/// asserts the two maps have identical keys, so a missing translation is a
/// failing build rather than an English word on a screen in Chinoz.
library;

const Map<String, String> kUz = <String, String>{
  'app.title': 'SihhatAI',
  'disclaimer.short': 'Bu tashxis emas. AI taklifi — qaror shifokorniki.',
  'disclaimer.long':
      'Barcha natijalar taklif sifatida beriladi va litsenziyali tibbiyot xodimi tomonidan tasdiqlanishi, tahrirlanishi yoki rad etilishi shart.',
  'login.title': 'Kirish',
  'login.email': 'Elektron pochta',
  'login.password': 'Parol',
  'login.submit': 'Kirish',
  'login.error': 'Kirish amalga oshmadi. Pochta yoki parolni tekshiring.',
  'patients.title': 'Bemorlar',
  'patients.search': 'Ism yoki raqam bo\'yicha qidirish',
  'patients.new': 'Yangi bemor',
  'patients.empty': 'Bemorlar topilmadi',
  'consultation.new': 'Yangi qabul',
  'consultation.complaint': 'Shikoyat',
  'consultation.complaintHint':
      'Bemor nima deyapti? O\'z so\'zlari bilan yozing.',
  'consultation.symptoms': 'Belgilar',
  'consultation.vitals': 'Ko\'rsatkichlar',
  'consultation.analyze': 'Tahlil qilish',
  'consultation.mic': 'Ovozli yozish',
  'consultation.recording': 'Yozib olinmoqda...',
  'consultation.summary': 'Xulosa',
  'consultation.print': 'Bemorga chop etish',
  'suggestion.title': 'AI takliflari',
  'suggestion.why': 'Nima uchun',
  'suggestion.tests': 'Tavsiya etilgan tekshiruvlar',
  'suggestion.treatment': 'Davolash',
  'suggestion.referral': 'Yo\'naltirish',
  'suggestion.insufficient': 'Ma\'lumot yetarli emas. Quyidagilarni so\'rang:',
  'suggestion.notAvailable': 'Mahalliy mavjud emas',
  'suggestion.substitute': 'O\'rniga',
  'suggestion.pediatricWeight': 'Bolalar dozasi uchun vazn kerak',
  'suggestion.offline': 'Oflayn rejim — faqat qoidalar asosida',
  'decision.accept': 'Qabul qilish',
  'decision.edit': 'Tahrirlash',
  'decision.reject': 'Rad etish',
  'decision.reasonHint': 'Sababini yozing',
  'decision.editHint': 'Yakuniy xulosani yozing',
  'decision.required': 'Davom etish uchun qaror qabul qiling',
  'redflag.banner': 'SHOSHILINCH: xavfli belgilar aniqlandi',
  'redflag.referNow': 'Bemorni zudlik bilan yo\'naltiring',
  'sync.pending': 'Yuborilmagan yozuvlar',
  'sync.lastSynced': 'Oxirgi sinxronizatsiya',
  'sync.never': 'hali sinxronlanmagan',
  'sync.retry': 'Qayta urinish',
  'sync.offline': 'Internet yo\'q — yozuvlar saqlanmoqda',
  'sync.online': 'Ulangan',
  'sync.syncing': 'Yuborilmoqda...',
  'sync.allSent': 'Hammasi yuborildi',
  'vitals.temperature': 'Harorat (°C)',
  'vitals.pulse': 'Puls',
  'vitals.systolic': 'Yuqori bosim',
  'vitals.diastolic': 'Pastki bosim',
  'vitals.respiratory': 'Nafas olish',
  'vitals.spo2': 'SpO2 (%)',
  'vitals.weight': 'Vazn (kg)',
  'vitals.glucose': 'Qand (mmol/l)',
  'common.save': 'Saqlash',
  'common.cancel': 'Bekor qilish',
  'common.next': 'Keyingi',
  'common.back': 'Orqaga',
  'common.done': 'Tayyor',
  'common.language': 'Til',
  'common.retry': 'Qayta urinish',
  'common.error': 'Xatolik yuz berdi',
};

const Map<String, String> kRu = <String, String>{
  'app.title': 'SihhatAI',
  'disclaimer.short': 'Это не диагноз. Предложение ИИ — решает врач.',
  'disclaimer.long':
      'Все результаты являются предложениями и должны быть подтверждены, изменены или отклонены лицензированным медработником.',
  'login.title': 'Вход',
  'login.email': 'Электронная почта',
  'login.password': 'Пароль',
  'login.submit': 'Войти',
  'login.error': 'Вход не выполнен. Проверьте почту или пароль.',
  'patients.title': 'Пациенты',
  'patients.search': 'Поиск по имени или номеру',
  'patients.new': 'Новый пациент',
  'patients.empty': 'Пациенты не найдены',
  'consultation.new': 'Новый приём',
  'consultation.complaint': 'Жалобы',
  'consultation.complaintHint': 'Что говорит пациент? Запишите его словами.',
  'consultation.symptoms': 'Симптомы',
  'consultation.vitals': 'Показатели',
  'consultation.analyze': 'Анализировать',
  'consultation.mic': 'Голосовой ввод',
  'consultation.recording': 'Идёт запись...',
  'consultation.summary': 'Заключение',
  'consultation.print': 'Печать для пациента',
  'suggestion.title': 'Предложения ИИ',
  'suggestion.why': 'Почему',
  'suggestion.tests': 'Рекомендуемые исследования',
  'suggestion.treatment': 'Лечение',
  'suggestion.referral': 'Направление',
  'suggestion.insufficient': 'Недостаточно данных. Уточните:',
  'suggestion.notAvailable': 'Локально недоступно',
  'suggestion.substitute': 'Замена',
  'suggestion.pediatricWeight': 'Для детской дозы нужен вес',
  'suggestion.offline': 'Офлайн-режим — только правила',
  'decision.accept': 'Принять',
  'decision.edit': 'Изменить',
  'decision.reject': 'Отклонить',
  'decision.reasonHint': 'Укажите причину',
  'decision.editHint': 'Запишите итоговое заключение',
  'decision.required': 'Примите решение, чтобы продолжить',
  'redflag.banner': 'СРОЧНО: выявлены тревожные признаки',
  'redflag.referNow': 'Немедленно направьте пациента',
  'sync.pending': 'Неотправленные записи',
  'sync.lastSynced': 'Последняя синхронизация',
  'sync.never': 'ещё не синхронизировано',
  'sync.retry': 'Повторить',
  'sync.offline': 'Нет интернета — записи сохраняются',
  'sync.online': 'Подключено',
  'sync.syncing': 'Отправка...',
  'sync.allSent': 'Всё отправлено',
  'vitals.temperature': 'Температура (°C)',
  'vitals.pulse': 'Пульс',
  'vitals.systolic': 'Верхнее давление',
  'vitals.diastolic': 'Нижнее давление',
  'vitals.respiratory': 'Частота дыхания',
  'vitals.spo2': 'SpO2 (%)',
  'vitals.weight': 'Вес (кг)',
  'vitals.glucose': 'Сахар (ммоль/л)',
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.next': 'Далее',
  'common.back': 'Назад',
  'common.done': 'Готово',
  'common.language': 'Язык',
  'common.retry': 'Повторить',
  'common.error': 'Произошла ошибка',
};

/// Uzbek is the default; there is no English fallback on clinical surfaces.
String tr(String key, String language) {
  final Map<String, String> table = language == 'ru' ? kRu : kUz;
  return table[key] ?? kUz[key] ?? key;
}
