"""initial schema

Revision ID: a980669ea994
Revises: 
Create Date: 2026-08-19 19:02:30.815657
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.models.types


revision = 'a980669ea994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # pgvector backs protocol_chunks.embedding. Requires the extension to
        # be installable by the migration role (it is in the compose image).
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('gov', 'private', name='clinictype', native_enum=False, length=16), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('offline_mode', sa.Boolean(), nullable=False),
    sa.Column('default_language', sa.String(length=2), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinics'))
    )
    op.create_table('formulary_items',
    sa.Column('generic_name', sa.String(length=160), nullable=False),
    sa.Column('name_uz', sa.String(length=160), nullable=True),
    sa.Column('name_ru', sa.String(length=160), nullable=True),
    sa.Column('form', sa.String(length=60), nullable=False),
    sa.Column('strength', sa.String(length=60), nullable=True),
    sa.Column('atc_code', sa.String(length=16), nullable=True),
    sa.Column('availability_tier', sa.Integer(), nullable=False),
    sa.Column('controlled', sa.Boolean(), nullable=False),
    sa.Column('pediatric_ok', sa.Boolean(), nullable=False),
    sa.Column('pregnancy_category', sa.String(length=8), nullable=True),
    sa.Column('typical_cost_uzs', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formulary_items')),
    sa.UniqueConstraint('generic_name', 'form', name='uq_generic_form')
    )
    op.create_index(op.f('ix_formulary_items_generic_name'), 'formulary_items', ['generic_name'], unique=False)
    op.create_table('protocol_chunks',
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('publisher', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('filters', app.models.types.JSONBType(), nullable=False),
    sa.Column('embedding', app.models.types.Vector(), nullable=True),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocol_chunks')),
    sa.UniqueConstraint('source_id', 'chunk_index', name='uq_source_chunk')
    )
    op.create_index(op.f('ix_protocol_chunks_language'), 'protocol_chunks', ['language'], unique=False)
    op.create_index(op.f('ix_protocol_chunks_source_id'), 'protocol_chunks', ['source_id'], unique=False)
    op.create_table('sync_merge_logs',
    sa.Column('clinic_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('resolution', app.models.types.JSONBType(), nullable=False),
    sa.Column('client_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_merge_logs'))
    )
    op.create_index(op.f('ix_sync_merge_logs_clinic_id'), 'sync_merge_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_sync_merge_logs_device_id'), 'sync_merge_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_merge_logs_entity_id'), 'sync_merge_logs', ['entity_id'], unique=False)
    op.create_table('terminology_entries',
    sa.Column('term_uz', sa.String(length=160), nullable=False),
    sa.Column('term_ru', sa.String(length=160), nullable=True),
    sa.Column('term_en', sa.String(length=160), nullable=False),
    sa.Column('icd10', sa.String(length=16), nullable=True),
    sa.Column('concept', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('synonyms', app.models.types.JSONBType(), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminology_entries'))
    )
    op.create_index(op.f('ix_terminology_entries_concept'), 'terminology_entries', ['concept'], unique=False)
    op.create_index(op.f('ix_terminology_entries_icd10'), 'terminology_entries', ['icd10'], unique=False)
    op.create_index(op.f('ix_terminology_entries_term_ru'), 'terminology_entries', ['term_ru'], unique=False)
    op.create_index(op.f('ix_terminology_entries_term_uz'), 'terminology_entries', ['term_uz'], unique=False)
    op.create_table('patients',
    sa.Column('clinic_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('pii_blob', sa.LargeBinary(), nullable=False),
    sa.Column('mrn', sa.String(length=32), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'unknown', name='sex', native_enum=False, length=8), nullable=False),
    sa.Column('chronic_flags', app.models.types.JSONBType(), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_patients_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_table('users',
    sa.Column('clinic_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'feldsher', 'nurse', 'admin', 'superadmin', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('license_no', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_users_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('clinic_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', app.models.types.JSONBType(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_logs_hash'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_clinic_id'), 'audit_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_seq'), 'audit_logs', ['seq'], unique=True)
    op.create_table('consultations',
    sa.Column('patient_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('clinic_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('structured_symptoms', app.models.types.JSONBType(), nullable=False),
    sa.Column('vitals', app.models.types.JSONBType(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'analyzing', 'awaiting_decision', 'completed', 'cancelled', name='consultationstatus', native_enum=False, length=24), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_offline', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_consultations_clinic_id_clinics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consultations_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consultations_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index(op.f('ix_consultations_client_uuid'), 'consultations', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_consultations_clinic_id'), 'consultations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_table('sync_receipts',
    sa.Column('clinic_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('operation_id', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('server_entity_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=True),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_receipts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_receipts'))
    )
    op.create_index(op.f('ix_sync_receipts_clinic_id'), 'sync_receipts', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_sync_receipts_operation_id'), 'sync_receipts', ['operation_id'], unique=True)
    op.create_table('ai_suggestions',
    sa.Column('consultation_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('kind', sa.Enum('diagnosis', 'treatment', 'referral', 'risk', name='suggestionkind', native_enum=False, length=16), nullable=False),
    sa.Column('payload', app.models.types.JSONBType(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_ai_suggestions_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_suggestions'))
    )
    op.create_index(op.f('ix_ai_suggestions_consultation_id'), 'ai_suggestions', ['consultation_id'], unique=False)
    op.create_table('clinician_decisions',
    sa.Column('ai_suggestion_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('user_id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('action', sa.Enum('accept', 'edit', 'reject', name='decisionaction', native_enum=False, length=8), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.types.GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_suggestion_id'], ['ai_suggestions.id'], name=op.f('fk_clinician_decisions_ai_suggestion_id_ai_suggestions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clinician_decisions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinician_decisions'))
    )
    op.create_index(op.f('ix_clinician_decisions_ai_suggestion_id'), 'clinician_decisions', ['ai_suggestion_id'], unique=True)
    op.create_index(op.f('ix_clinician_decisions_user_id'), 'clinician_decisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinician_decisions_user_id'), table_name='clinician_decisions')
    op.drop_index(op.f('ix_clinician_decisions_ai_suggestion_id'), table_name='clinician_decisions')
    op.drop_table('clinician_decisions')
    op.drop_index(op.f('ix_ai_suggestions_consultation_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_sync_receipts_operation_id'), table_name='sync_receipts')
    op.drop_index(op.f('ix_sync_receipts_clinic_id'), table_name='sync_receipts')
    op.drop_table('sync_receipts')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_clinic_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_client_uuid'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_audit_logs_seq'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_clinic_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_terminology_entries_term_uz'), table_name='terminology_entries')
    op.drop_index(op.f('ix_terminology_entries_term_ru'), table_name='terminology_entries')
    op.drop_index(op.f('ix_terminology_entries_icd10'), table_name='terminology_entries')
    op.drop_index(op.f('ix_terminology_entries_concept'), table_name='terminology_entries')
    op.drop_table('terminology_entries')
    op.drop_index(op.f('ix_sync_merge_logs_entity_id'), table_name='sync_merge_logs')
    op.drop_index(op.f('ix_sync_merge_logs_device_id'), table_name='sync_merge_logs')
    op.drop_index(op.f('ix_sync_merge_logs_clinic_id'), table_name='sync_merge_logs')
    op.drop_table('sync_merge_logs')
    op.drop_index(op.f('ix_protocol_chunks_source_id'), table_name='protocol_chunks')
    op.drop_index(op.f('ix_protocol_chunks_language'), table_name='protocol_chunks')
    op.drop_table('protocol_chunks')
    op.drop_index(op.f('ix_formulary_items_generic_name'), table_name='formulary_items')
    op.drop_table('formulary_items')
    op.drop_table('clinics')
    # ### end Alembic commands ###
